In [35]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [3]:
data=pd.read_csv("Test_data.csv")
data.head()

employee_id         department     region   education gender  \
0         8724         Technology  region_26  Bachelor's      m   
1        74430                 HR   region_4  Bachelor's      f   
2        72255  Sales & Marketing  region_13  Bachelor's      m   
3        38562        Procurement   region_2  Bachelor's      f   
4        64486            Finance  region_29  Bachelor's      m   

  recruitment_channel  no_of_trainings  age  previous_year_rating  \
0            sourcing                1   24                   NaN   
1               other                1   31                   3.0   
2               other                1   31                   1.0   
3               other                3   31                   2.0   
4            sourcing                1   30                   4.0   

   length_of_service  KPIs_met >80%  awards_won?  avg_training_score  
0                  1              1            0                  77  
1                  5              0            0                  51  
2                  4              0            0                  47  
3                  9              0            0                  65  
4                  7              0            0                  61

In [5]:
data.isnull().sum()

employee_id                0
department                 0
region                     0
education               1034
gender                     0
recruitment_channel        0
no_of_trainings            0
age                        0
previous_year_rating    1812
length_of_service          0
KPIs_met >80%              0
awards_won?                0
avg_training_score         0
dtype: int64

In [7]:
data.dropna(inplace=True)
data.isnull().sum()

employee_id             0
department              0
region                  0
education               0
gender                  0
recruitment_channel     0
no_of_trainings         0
age                     0
previous_year_rating    0
length_of_service       0
KPIs_met >80%           0
awards_won?             0
avg_training_score      0
dtype: int64

In [9]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [11]:
cat_col=['department','region', 'education', 'gender', 'recruitment_channel','previous_year_rating']
for i in cat_col:
    data[i]=le.fit_transform(data[i])

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20819 entries, 1 to 23489
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   employee_id           20819 non-null  int64
 1   department            20819 non-null  int32
 2   region                20819 non-null  int32
 3   education             20819 non-null  int32
 4   gender                20819 non-null  int32
 5   recruitment_channel   20819 non-null  int32
 6   no_of_trainings       20819 non-null  int64
 7   age                   20819 non-null  int64
 8   previous_year_rating  20819 non-null  int64
 9   length_of_service     20819 non-null  int64
 10  KPIs_met >80%         20819 non-null  int64
 11  awards_won?           20819 non-null  int64
 12  avg_training_score    20819 non-null  int64
dtypes: int32(5), int64(8)
memory usage: 1.8 MB


In [21]:
#deviding the data into predictors and outcome variables
x = data.drop(columns=['KPIs_met >80%'])
y = data['KPIs_met >80%']
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.20, random_state=42)
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((16655, 12), (4164, 12), (16655,), (4164,))

firstly we are checking model accuracy without using variable scaling
1)XGBoost
<span style="font-size: 20px;">This text will be bold and increased in size</span>

In [25]:
from xgboost import XGBClassifier
model_xgb = XGBClassifier()
model_xgb.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [37]:
y_predict = model_xgb.predict(x_test)

# Calculate and print the accuracy score
print(accuracy_score(y_test, y_predict))

0.7089337175792507


In [41]:
from sklearn.metrics import confusion_matrix, classification_report

# Print the confusion matrix
print('Confusion matrix:\n', confusion_matrix(y_test, y_predict))

# Print the classification report
print('\nClassification Report:\n', classification_report(y_test, y_predict))

Confusion matrix:
 [[2249  402]
 [ 810  703]]

Classification Report:
               precision    recall  f1-score   support

           0       0.74      0.85      0.79      2651
           1       0.64      0.46      0.54      1513

    accuracy                           0.71      4164
   macro avg       0.69      0.66      0.66      4164
weighted avg       0.70      0.71      0.70      4164



In [45]:
from catboost import CatBoostClassifier
model_cat = CatBoostClassifier()
model_cat.fit(x_train,y_train)

Learning rate set to 0.03424
0:	learn: 0.6838654	total: 139ms	remaining: 2m 18s
1:	learn: 0.6764263	total: 143ms	remaining: 1m 11s
2:	learn: 0.6694025	total: 147ms	remaining: 48.7s
3:	learn: 0.6626117	total: 150ms	remaining: 37.4s
4:	learn: 0.6565299	total: 154ms	remaining: 30.6s
5:	learn: 0.6506667	total: 157ms	remaining: 26s
6:	learn: 0.6454200	total: 160ms	remaining: 22.7s
7:	learn: 0.6403897	total: 164ms	remaining: 20.3s
8:	learn: 0.6360086	total: 167ms	remaining: 18.4s
9:	learn: 0.6314962	total: 170ms	remaining: 16.9s
10:	learn: 0.6268831	total: 174ms	remaining: 15.6s
11:	learn: 0.6234746	total: 177ms	remaining: 14.5s
12:	learn: 0.6199890	total: 180ms	remaining: 13.7s
13:	learn: 0.6165114	total: 183ms	remaining: 12.9s
14:	learn: 0.6128522	total: 186ms	remaining: 12.2s
15:	learn: 0.6099699	total: 190ms	remaining: 11.7s
16:	learn: 0.6076423	total: 193ms	remaining: 11.2s
17:	learn: 0.6044547	total: 196ms	remaining: 10.7s
18:	learn: 0.6020482	total: 199ms	remaining: 10.3s
19:	learn: 0

In [47]:
y_predict1 = model_cat.predict(x_test)
print(accuracy_score(y_test,y_predict1))
print(classification_report(y_test,y_predict1))

0.7158981748318924
              precision    recall  f1-score   support

           0       0.74      0.86      0.79      2651
           1       0.65      0.47      0.54      1513

    accuracy                           0.72      4164
   macro avg       0.70      0.66      0.67      4164
weighted avg       0.71      0.72      0.70      4164



In [59]:
from lightgbm import LGBMClassifier
model_light = LGBMClassifier()
model_light.fit(x_train,y_train)

[LightGBM] [Info] Number of positive: 6032, number of negative: 10623
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000392 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 457
[LightGBM] [Info] Number of data points in the train set: 16655, number of used features: 12
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.362174 -> initscore=-0.565943
[LightGBM] [Info] Start training from score -0.565943


LGBMClassifier()

In [61]:
y_predict2 = model_light.predict(x_test)
print(accuracy_score(y_test,y_predict2))
print(classification_report(y_test,y_predict2))

0.718059558117195
              precision    recall  f1-score   support

           0       0.74      0.86      0.80      2651
           1       0.66      0.47      0.55      1513

    accuracy                           0.72      4164
   macro avg       0.70      0.66      0.67      4164
weighted avg       0.71      0.72      0.71      4164



In [69]:
from sklearn.preprocessing import StandardScaler
SC=StandardScaler()
data_scale=SC.fit_transform(data)
data_scale

array([[ 1.56232111, -1.18849603,  1.43479131, ..., -0.75392599,
        -0.15460282, -0.93598885],
       [ 1.46627551,  0.82109568, -1.30248962, ..., -0.75392599,
        -0.15460282, -1.23710728],
       [-0.02157022,  0.01725899, -0.50411601, ..., -0.75392599,
        -0.15460282,  0.11792564],
       ...,
       [-0.59395784,  1.22301402,  0.18020422, ..., -0.75392599,
        -0.15460282,  0.79544209],
       [ 0.28078575, -1.18849603, -0.9603295 , ..., -0.75392599,
        -0.15460282, -1.01126846],
       [-1.46066452,  1.22301402, -0.84627613, ...,  1.32639014,
        -0.15460282,  1.92463619]])

In [71]:
data_scale_df=pd.DataFrame(data_scale,columns=data.columns)
data_scale_df

employee_id  department    region  education    gender  \
0         1.562321   -1.188496  1.434791  -0.681088 -1.529572   
1         1.466276    0.821096 -1.302490  -0.681088  0.653778   
2        -0.021570    0.017259 -0.504116  -0.681088 -1.529572   
3         1.123205   -1.590414  0.636418  -0.681088  0.653778   
4         0.317129    0.017259  1.776951  -0.681088  0.653778   
...            ...         ...       ...        ...       ...   
20814     0.374756    0.821096 -0.390063  -0.681088  0.653778   
20815     0.637104   -0.786578 -0.504116   0.402729  0.653778   
20816    -0.593958    1.223014  0.180204  -0.681088  0.653778   
20817     0.280786   -1.188496 -0.960330  -0.681088 -1.529572   
20818    -1.460665    1.223014 -0.846276   1.486546  0.653778   

       recruitment_channel  no_of_trainings       age  previous_year_rating  \
0                -0.881086        -0.422224 -0.606824             -0.276085   
1                -0.881086        -0.422224 -0.606824             -1.860596   
2                -0.881086         2.938617 -0.606824             -1.068340   
3                 1.157969        -0.422224 -0.738998              0.516170   
4                 1.157969        -0.422224  0.054047             -0.276085   
...                    ...              ...       ...                   ...   
20814            -0.881086        -0.422224 -1.003346              0.516170   
20815             1.157969        -0.422224 -1.532043             -0.276085   
20816             1.157969        -0.422224 -0.606824             -0.276085   
20817             1.157969        -0.422224 -1.267695              0.516170   
20818            -0.881086         2.938617  0.582743              1.308426   

       length_of_service  KPIs_met >80%  awards_won?  avg_training_score  
0              -0.304192      -0.753926    -0.154603           -0.935989  
1              -0.545283      -0.753926    -0.154603           -1.237107  
2               0.660172      -0.753926    -0.154603            0.117926  
3               0.177990      -0.753926    -0.154603           -0.183193  
4              -1.027466      -0.753926    -0.154603            0.343764  
...                  ...            ...          ...                 ...  
20814          -1.027466      -0.753926    -0.154603           -0.935989  
20815          -1.268557      -0.753926    -0.154603           -0.183193  
20816           0.177990      -0.753926    -0.154603            0.795442  
20817          -0.545283      -0.753926    -0.154603           -1.011268  
20818          -0.304192       1.326390    -0.154603            1.924636  

[20819 rows x 13 columns]

In [77]:
from sklearn.model_selection import train_test_split

# Separate the predictors and the target variable
x = data_norm_df.iloc[:, :-1]
y = data_norm_df['KPIs_met >80%']

# Split the data into training and test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42)

# Display the shapes of the resulting datasets
x_train.shape, x_test.shape, y_train.shape, y_test.shape


((16655, 12), (4164, 12), (16655,), (4164,))

In [81]:
y_test.value_counts()

KPIs_met >80%
0.0    2651
1.0    1513
Name: count, dtype: int64

In [83]:
from sklearn.preprocessing import RobustScaler
RS=RobustScaler()
data_robust=RS.fit_transform(data)
data_robust

array([[ 0.90119069, -1.        ,  1.4       , ...,  0.        ,
         0.        , -0.375     ],
       [ 0.84597223,  0.66666667, -1.        , ...,  0.        ,
         0.        , -0.54166667],
       [-0.00941887,  0.        , -0.3       , ...,  0.        ,
         0.        ,  0.20833333],
       ...,
       [-0.33849552,  1.        ,  0.3       , ...,  0.        ,
         0.        ,  0.58333333],
       [ 0.16441138, -1.        , -0.7       , ...,  0.        ,
         0.        , -0.41666667],
       [-0.83678184,  1.        , -0.6       , ...,  1.        ,
         0.        ,  1.20833333]])

In [85]:
data_robust_df=pd.DataFrame(data_robust,columns=data.columns)
data_robust_df

employee_id  department  region  education  gender  \
0         0.901191   -1.000000     1.4        0.0    -1.0   
1         0.845972    0.666667    -1.0        0.0     0.0   
2        -0.009419    0.000000    -0.3        0.0    -1.0   
3         0.648734   -1.333333     0.7        0.0     0.0   
4         0.185306    0.000000     1.7        0.0     0.0   
...            ...         ...     ...        ...     ...   
20814     0.218437    0.666667    -0.2        0.0     0.0   
20815     0.369266   -0.666667    -0.3        0.5     0.0   
20816    -0.338496    1.000000     0.3        0.0     0.0   
20817     0.164411   -1.000000    -0.7        0.0    -1.0   
20818    -0.836782    1.000000    -0.6        1.0     0.0   

       recruitment_channel  no_of_trainings       age  previous_year_rating  \
0                      0.0              0.0 -0.333333                   0.0   
1                      0.0              0.0 -0.333333                  -2.0   
2                      0.0              2.0 -0.333333                  -1.0   
3                      1.0              0.0 -0.444444                   1.0   
4                      1.0              0.0  0.222222                   0.0   
...                    ...              ...       ...                   ...   
20814                  0.0              0.0 -0.666667                   1.0   
20815                  1.0              0.0 -1.111111                   0.0   
20816                  1.0              0.0 -0.333333                   0.0   
20817                  1.0              0.0 -0.888889                   1.0   
20818                  0.0              2.0  0.666667                   2.0   

       length_of_service  KPIs_met >80%  awards_won?  avg_training_score  
0                    0.0            0.0          0.0           -0.375000  
1                   -0.2            0.0          0.0           -0.541667  
2                    0.8            0.0          0.0            0.208333  
3                    0.4            0.0          0.0            0.041667  
4                   -0.6            0.0          0.0            0.333333  
...                  ...            ...          ...                 ...  
20814               -0.6            0.0          0.0           -0.375000  
20815               -0.8            0.0          0.0            0.041667  
20816                0.4            0.0          0.0            0.583333  
20817               -0.2            0.0          0.0           -0.416667  
20818                0.0            1.0          0.0            1.208333  

[20819 rows x 13 columns]

In [89]:
data_robust_df['KPIs_met >80%'].value_counts()

KPIs_met >80%
0.0    13274
1.0     7545
Name: count, dtype: int64

In [95]:
#deviding the data into predictors and outcome variables
x_robust=data_robust_df.iloc[:,:-1]
y_robust=data_robust_df['KPIs_met >80%']
x_train_robust, x_test_robust, y_train_robust, y_test_robust = train_test_split( x_robust, y_robust, test_size=0.20, random_state=42)
x_train_robust.shape,x_test_robust.shape,y_train_robust.shape,y_test_robust.shape


((16655, 12), (4164, 12), (16655,), (4164,))

In [97]:
import warnings
warnings.filterwarnings('ignore')
# Training the model
from xgboost import XGBClassifier
model_xgb_robust = XGBClassifier()
model_xgb_robust.fit(x_train_robust,y_train_robust)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [99]:
y_predict_xgb_robust = model_xgb_robust.predict(x_test_robust)
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
print("accuracy_score is ",accuracy_score(y_test_robust,y_predict_xgb_robust))
print()
print("confusion matrix \n",confusion_matrix(y_test_robust,y_predict_xgb_robust))
print()
print(classification_report(y_test_robust,y_predict_xgb_robust)
     )

accuracy_score is  1.0

confusion matrix 
 [[2651    0]
 [   0 1513]]

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      2651
         1.0       1.00      1.00      1.00      1513

    accuracy                           1.00      4164
   macro avg       1.00      1.00      1.00      4164
weighted avg       1.00      1.00      1.00      4164



In [101]:
import warnings
warnings.filterwarnings('ignore')
# Training the model
from catboost import CatBoostClassifier
model_cat_robust = CatBoostClassifier()
model_cat_robust.fit(x_train_robust,y_train_robust)

Learning rate set to 0.03424
0:	learn: 0.5789345	total: 5.13ms	remaining: 5.12s
1:	learn: 0.4649069	total: 8.19ms	remaining: 4.08s
2:	learn: 0.3821406	total: 12.2ms	remaining: 4.05s
3:	learn: 0.3163198	total: 16.2ms	remaining: 4.03s
4:	learn: 0.2643096	total: 20.5ms	remaining: 4.08s
5:	learn: 0.2106246	total: 23.7ms	remaining: 3.93s
6:	learn: 0.1698497	total: 27.9ms	remaining: 3.96s
7:	learn: 0.1401317	total: 31.8ms	remaining: 3.95s
8:	learn: 0.1136049	total: 35.7ms	remaining: 3.93s
9:	learn: 0.0914522	total: 39.1ms	remaining: 3.87s
10:	learn: 0.0764150	total: 43ms	remaining: 3.87s
11:	learn: 0.0640980	total: 47.1ms	remaining: 3.88s
12:	learn: 0.0522094	total: 50.3ms	remaining: 3.82s
13:	learn: 0.0438306	total: 53.8ms	remaining: 3.79s
14:	learn: 0.0371648	total: 57.9ms	remaining: 3.8s
15:	learn: 0.0328249	total: 62.1ms	remaining: 3.82s
16:	learn: 0.0279292	total: 65.9ms	remaining: 3.81s
17:	learn: 0.0242782	total: 69.7ms	remaining: 3.81s
18:	learn: 0.0212125	total: 73.3ms	remaining: 3.

In [103]:
y_predict_cat_robust = model_cat_robust.predict(x_test_robust)
y_predict_cat_robust

array([0., 0., 1., ..., 0., 0., 0.])

In [105]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
print("accuracy_score of catboost model is ",accuracy_score(y_test_robust,y_predict_cat_robust))
print()
print("confusion matrix \n",confusion_matrix(y_test_robust,y_predict_cat_robust))
print()
print("classification_report \n",classification_report(y_test_robust,y_predict_cat_robust)
     )

accuracy_score of catboost model is  1.0

confusion matrix 
 [[2651    0]
 [   0 1513]]

classification_report 
               precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      2651
         1.0       1.00      1.00      1.00      1513

    accuracy                           1.00      4164
   macro avg       1.00      1.00      1.00      4164
weighted avg       1.00      1.00      1.00      4164



In [107]:
import warnings
warnings.filterwarnings('ignore')
# Training the model
from lightgbm import LGBMClassifier
model_light_robust = LGBMClassifier()
model_light_robust.fit(x_train_robust,y_train_robust)

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 6032, number of negative: 10623
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000502 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 396
[LightGBM] [Info] Number of data points in the train set: 16655, number of used features: 12
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.362174 -> initscore=-0.565943
[LightGBM] [Info] Start training from score -0.565943
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best 

LGBMClassifier()

In [109]:
y_predict_light_robust = model_light_robust.predict(x_test_robust)
y_predict_light_robust

array([0., 0., 1., ..., 0., 0., 0.])

In [111]:
print("accuracy_score of catboost model is ",accuracy_score(y_test_robust,y_predict_light_robust))
print()
print("confusion matrix \n",confusion_matrix(y_test_robust,y_predict_light_robust))
print()
print("classification_report \n",classification_report(y_test_robust,y_predict_light_robust)
     )

accuracy_score of catboost model is  1.0

confusion matrix 
 [[2651    0]
 [   0 1513]]

classification_report 
               precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      2651
         1.0       1.00      1.00      1.00      1513

    accuracy                           1.00      4164
   macro avg       1.00      1.00      1.00      4164
weighted avg       1.00      1.00      1.00      4164



In [113]:
from sklearn.preprocessing import MaxAbsScaler
ms=MaxAbsScaler()
data_maxabs=ms.fit_transform(data)
data_maxabs

array([[0.95063542, 0.25      , 0.84848485, ..., 0.        , 0.        ,
        0.51515152],
       [0.92285587, 0.875     , 0.12121212, ..., 0.        , 0.        ,
        0.47474747],
       [0.49252187, 0.625     , 0.33333333, ..., 0.        , 0.        ,
        0.65656566],
       ...,
       [0.32696852, 1.        , 0.51515152, ..., 0.        , 0.        ,
        0.74747475],
       [0.57997318, 0.25      , 0.21212121, ..., 0.        , 0.        ,
        0.50505051],
       [0.0762884 , 1.        , 0.24242424, ..., 1.        , 0.        ,
        0.8989899 ]])

In [115]:
data_maxabs_df=pd.DataFrame(data_maxabs,columns=data.columns)
data_maxabs_df

employee_id  department    region  education  gender  \
0         0.950635       0.250  0.848485        0.0     0.0   
1         0.922856       0.875  0.121212        0.0     1.0   
2         0.492522       0.625  0.333333        0.0     0.0   
3         0.823629       0.125  0.636364        0.0     1.0   
4         0.590485       0.625  0.939394        0.0     1.0   
...            ...         ...       ...        ...     ...   
20814     0.607152       0.875  0.363636        0.0     1.0   
20815     0.683032       0.375  0.333333        0.5     1.0   
20816     0.326969       1.000  0.515152        0.0     1.0   
20817     0.579973       0.250  0.212121        0.0     0.0   
20818     0.076288       1.000  0.242424        1.0     1.0   

       recruitment_channel  no_of_trainings       age  previous_year_rating  \
0                      0.0         0.111111  0.516667                  0.50   
1                      0.0         0.111111  0.516667                  0.00   
2                      0.0         0.333333  0.516667                  0.25   
3                      1.0         0.111111  0.500000                  0.75   
4                      1.0         0.111111  0.600000                  0.50   
...                    ...              ...       ...                   ...   
20814                  0.0         0.111111  0.466667                  0.75   
20815                  1.0         0.111111  0.400000                  0.50   
20816                  1.0         0.111111  0.516667                  0.50   
20817                  1.0         0.111111  0.433333                  0.75   
20818                  0.0         0.333333  0.666667                  1.00   

       length_of_service  KPIs_met >80%  awards_won?  avg_training_score  
0               0.147059            0.0          0.0            0.515152  
1               0.117647            0.0          0.0            0.474747  
2               0.264706            0.0          0.0            0.656566  
3               0.205882            0.0          0.0            0.616162  
4               0.058824            0.0          0.0            0.686869  
...                  ...            ...          ...                 ...  
20814           0.058824            0.0          0.0            0.515152  
20815           0.029412            0.0          0.0            0.616162  
20816           0.205882            0.0          0.0            0.747475  
20817           0.117647            0.0          0.0            0.505051  
20818           0.147059            1.0          0.0            0.898990  

[20819 rows x 13 columns]

In [123]:
x_maxabs=data_maxabs_df.iloc[:,:-1]
y_maxabs=data_maxabs_df['KPIs_met >80%']
x_train_maxabs, x_test_maxabs, y_train_maxabs, y_test_maxabs = train_test_split( x_maxabs, y_maxabs, test_size=0.20, random_state=42)

In [125]:
import warnings
warnings.filterwarnings('ignore')
# Training the model
from xgboost import XGBClassifier
model_xgb_maxabs = XGBClassifier()
model_xgb_maxabs.fit(x_train_maxabs,y_train_maxabs)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [127]:
y_predict_xgb_maxabs = model_xgb_maxabs.predict(x_test_maxabs)
y_predict_xgb_maxabs

array([0, 0, 1, ..., 0, 0, 0])

In [129]:
print("Accuracy score is=",accuracy_score(y_test_maxabs,y_predict_xgb_maxabs))
print(classification_report(y_test_maxabs,y_predict_xgb_maxabs)
     )

Accuracy score is= 1.0
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      2651
         1.0       1.00      1.00      1.00      1513

    accuracy                           1.00      4164
   macro avg       1.00      1.00      1.00      4164
weighted avg       1.00      1.00      1.00      4164



In [131]:
from catboost import CatBoostClassifier
model_cat_Maxabs = CatBoostClassifier()
model_cat_Maxabs.fit(x_train_maxabs,y_train_maxabs)

Learning rate set to 0.03424
0:	learn: 0.5789345	total: 4.75ms	remaining: 4.75s
1:	learn: 0.4649069	total: 7.73ms	remaining: 3.86s
2:	learn: 0.3821406	total: 11.9ms	remaining: 3.95s
3:	learn: 0.3163198	total: 15.8ms	remaining: 3.93s
4:	learn: 0.2643096	total: 20ms	remaining: 3.98s
5:	learn: 0.2106246	total: 22.9ms	remaining: 3.79s
6:	learn: 0.1698497	total: 26.8ms	remaining: 3.81s
7:	learn: 0.1401317	total: 30.9ms	remaining: 3.83s
8:	learn: 0.1136049	total: 34.6ms	remaining: 3.81s
9:	learn: 0.0914522	total: 38.1ms	remaining: 3.77s
10:	learn: 0.0764150	total: 41.8ms	remaining: 3.76s
11:	learn: 0.0640980	total: 45.9ms	remaining: 3.78s
12:	learn: 0.0522094	total: 49.1ms	remaining: 3.73s
13:	learn: 0.0438306	total: 52.5ms	remaining: 3.7s
14:	learn: 0.0371648	total: 56.4ms	remaining: 3.7s
15:	learn: 0.0328249	total: 60.2ms	remaining: 3.7s
16:	learn: 0.0279292	total: 64.2ms	remaining: 3.71s
17:	learn: 0.0242782	total: 68.2ms	remaining: 3.72s
18:	learn: 0.0212125	total: 79ms	remaining: 4.08s


In [133]:
y_predict_cat_maxabs = model_cat_Maxabs.predict(x_test_maxabs)
y_predict_cat_maxabs

array([0., 0., 1., ..., 0., 0., 0.])

In [135]:
print("Accuracy score is=",accuracy_score(y_test_maxabs,y_predict_cat_maxabs))
print("Confusion Matrix",confusion_matrix(y_test_maxabs,y_predict_cat_maxabs))
print(classification_report(y_test_maxabs,y_predict_cat_maxabs)
     )

Accuracy score is= 1.0
Confusion Matrix [[2651    0]
 [   0 1513]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      2651
         1.0       1.00      1.00      1.00      1513

    accuracy                           1.00      4164
   macro avg       1.00      1.00      1.00      4164
weighted avg       1.00      1.00      1.00      4164



In [137]:
from lightgbm import LGBMClassifier
model_light_maxabs = LGBMClassifier()
model_light_maxabs.fit(x_train_maxabs,y_train_maxabs)

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 6032, number of negative: 10623
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000515 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 399
[LightGBM] [Info] Number of data points in the train set: 16655, number of used features: 12
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.362174 -> initscore=-0.565943
[LightGBM] [Info] Start training from score -0.565943
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best 

LGBMClassifier()

In [151]:
y_predict_light_maxabs = model_light_maxabs.predict(x_test_maxabs)
print("Accuracy score is=",accuracy_score(y_test_maxabs,y_predict_light_maxabs))
print()
print("Confusion Matrix \n",confusion_matrix(y_test_maxabs,y_predict_light_maxabs))
print()
print("classification_report \n",classification_report(y_test_maxabs,y_predict_light_maxabs)
     )

Accuracy score is= 1.0

Confusion Matrix 
 [[2651    0]
 [   0 1513]]

classification_report 
               precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      2651
         1.0       1.00      1.00      1.00      1513

    accuracy                           1.00      4164
   macro avg       1.00      1.00      1.00      4164
weighted avg       1.00      1.00      1.00      4164

